if(CMAKE_SCRIPT_MODE_FILE)
  cmake_minimum_required(VERSION 3.13)
endif()

set(EREBRUS_SINGBOX_HELPER "${CMAKE_CURRENT_LIST_FILE}")

function(erebrus_fetch_singbox platform output_variable)
  set(version "1.11.15")
  if(DEFINED ENV{SING_BOX_VERSION} AND NOT "$ENV{SING_BOX_VERSION}" STREQUAL ""
      AND NOT "$ENV{SING_BOX_VERSION}" STREQUAL "v${version}"
      AND NOT "$ENV{SING_BOX_VERSION}" STREQUAL "${version}")
    message(FATAL_ERROR "Desktop sing-box is pinned to ${version}; remove the SING_BOX_VERSION override. Update the reviewed version and SHA256 pins together to upgrade.")
  endif()
  if(platform STREQUAL "windows-amd64")
    set(archive_hash "9acbda81d7a9a93d8d0616990cf8b804523adfcd0215d11a2dd9370746d2be28")
    set(extension "zip")
    set(binary_name "sing-box.exe")
  elseif(platform STREQUAL "linux-amd64")
    set(archive_hash "950af37eb2d7e55dddae34a18411cd617303fd99d2dc75bc76b6dd9fcd97d9c5")
    set(extension "tar.gz")
    set(binary_name "sing-box")
  elseif(platform STREQUAL "darwin-amd64")
    set(archive_hash "1b40a467b20af2a3defb915f0c3e4cf9f3fd45af383543187400f14034407b35")
    set(extension "tar.gz")
    set(binary_name "sing-box")
  elseif(platform STREQUAL "darwin-arm64")
    set(archive_hash "079a6b2acac2dd418c70757c46e290f2fad12f7b60c878af6038aebb560ee988")
    set(extension "tar.gz")
    set(binary_name "sing-box")
  else()
    message(FATAL_ERROR "Unsupported sing-box runtime target '${platform}'. Supported desktop build targets are Windows x64 and Linux x64.")
  endif()
  string(LENGTH "${archive_hash}" hash_length)
  if(NOT hash_length EQUAL 64)
    message(FATAL_ERROR "The trusted SHA256 pin for sing-box ${version} ${platform} is missing from scripts/singbox-runtime.cmake. Obtain and review the official v${version} release checksums before building; unverified downloads are not allowed.")
  endif()

  get_filename_component(root "${EREBRUS_SINGBOX_HELPER}" DIRECTORY)
  get_filename_component(root "${root}/.." ABSOLUTE)
  set(asset "sing-box-${version}-${platform}")
  set(cache "${root}/bin/sing-box/.cache/${asset}")
  set(destination "${root}/bin/sing-box/${platform}")
  file(MAKE_DIRECTORY "${cache}" "${destination}")
  file(LOCK "${cache}/fetch.lock" GUARD FUNCTION TIMEOUT 180)
  set(archive "${cache}/${asset}.${extension}")
  if(EXISTS "${archive}")
    file(SHA256 "${archive}" actual_hash)
    if(NOT actual_hash STREQUAL archive_hash)
      file(REMOVE "${archive}")
    endif()
  endif()
  if(NOT EXISTS "${archive}")
    set(url "https://github.com/SagerNet/sing-box/releases/download/v${version}/${asset}.${extension}")
    message(STATUS "Downloading pinned sing-box ${version} (${platform})")
    file(DOWNLOAD "${url}" "${archive}.part"
      TLS_VERIFY ON TIMEOUT 180 INACTIVITY_TIMEOUT 30 STATUS download_status)
    list(GET download_status 0 download_code)
    list(GET download_status 1 download_message)
    if(NOT download_code EQUAL 0)
      file(REMOVE "${archive}.part")
      message(FATAL_ERROR "Cannot download sing-box: ${download_message}. Check HTTPS access to GitHub, then retry the build or run cmake -DSINGBOX_PLATFORM=${platform} -P \"${EREBRUS_SINGBOX_HELPER}\" on a connected machine and copy bin/sing-box (including .cache) here.")
    endif()
    file(SHA256 "${archive}.part" actual_hash)
    if(NOT actual_hash STREQUAL archive_hash)
      file(REMOVE "${archive}.part")
      message(FATAL_ERROR "sing-box archive SHA256 mismatch: expected ${archive_hash}, got ${actual_hash}. Download rejected; do not bypass the version/hash pin.")
    endif()
    file(RENAME "${archive}.part" "${archive}")
  endif()
  set(work "${cache}/extracted")
  file(REMOVE_RECURSE "${work}")
  file(MAKE_DIRECTORY "${work}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${archive}"
    WORKING_DIRECTORY "${work}" RESULT_VARIABLE extract_result)
  if(NOT extract_result EQUAL 0 OR NOT EXISTS "${work}/${asset}/${binary_name}")
    message(FATAL_ERROR "Cannot extract verified sing-box archive ${archive}. Remove this cache file and retry.")
  endif()
  set(binary "${destination}/${binary_name}")
  file(SHA256 "${work}/${asset}/${binary_name}" expected_binary_hash)
  if(EXISTS "${binary}")
    file(SHA256 "${binary}" actual_binary_hash)
    if(NOT actual_binary_hash STREQUAL expected_binary_hash)
      file(REMOVE "${binary}")
    endif()
  endif()
  file(COPY "${work}/${asset}/${binary_name}" DESTINATION "${destination}"
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
  file(REMOVE_RECURSE "${work}")
  set(${output_variable} "${binary}" PARENT_SCOPE)
endfunction()

function(erebrus_bundle_singbox target platform)
  if(platform STREQUAL "windows-amd64")
    set(expected_system "Windows")
    set(expected_flutter "windows-x64")
  elseif(platform STREQUAL "linux-amd64")
    set(expected_system "Linux")
    set(expected_flutter "linux-x64")
  else()
    message(FATAL_ERROR "Unsupported desktop runtime target ${platform}")
  endif()
  set(target_arch "${CMAKE_SYSTEM_PROCESSOR}")
  if(CMAKE_GENERATOR_PLATFORM)
    set(target_arch "${CMAKE_GENERATOR_PLATFORM}")
  elseif(CMAKE_VS_PLATFORM_NAME)
    set(target_arch "${CMAKE_VS_PLATFORM_NAME}")
  endif()
  string(TOLOWER "${target_arch}" target_arch)
  if(NOT CMAKE_SYSTEM_NAME STREQUAL expected_system
      OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8
      OR NOT target_arch MATCHES "^(amd64|x86_64|x64)$")
    message(FATAL_ERROR "sing-box ${platform} cannot be bundled for ${CMAKE_SYSTEM_NAME}/${target_arch}. Build the supported x64 target; no runtime is pinned for this OS/architecture.")
  endif()
  if(FLUTTER_TARGET_PLATFORM AND NOT FLUTTER_TARGET_PLATFORM STREQUAL expected_flutter)
    message(FATAL_ERROR "sing-box ${platform} does not match Flutter target ${FLUTTER_TARGET_PLATFORM}.")
  endif()
  erebrus_fetch_singbox("${platform}" binary)
  set(EREBRUS_SINGBOX_BINARY "${binary}" PARENT_SCOPE)
  add_custom_target(erebrus_singbox_runtime ALL
    COMMAND "${CMAKE_COMMAND}" "-DSINGBOX_PLATFORM=${platform}"
      "-DSINGBOX_OUTPUT_DIRECTORY=$<TARGET_FILE_DIR:${target}>"
      -P "${EREBRUS_SINGBOX_HELPER}"
    DEPENDS ${target}
    VERBATIM)
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
  if(NOT DEFINED SINGBOX_PLATFORM)
    message(FATAL_ERROR "Usage: cmake -DSINGBOX_PLATFORM=windows-amd64 (or linux-amd64) -P scripts/singbox-runtime.cmake")
  endif()
  erebrus_fetch_singbox("${SINGBOX_PLATFORM}" binary)
  if(DEFINED SINGBOX_OUTPUT_DIRECTORY)
    file(MAKE_DIRECTORY "${SINGBOX_OUTPUT_DIRECTORY}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
      "${binary}" "${SINGBOX_OUTPUT_DIRECTORY}/"
      RESULT_VARIABLE copy_result)
    if(NOT copy_result EQUAL 0)
      message(FATAL_ERROR "Cannot package sing-box beside the executable in ${SINGBOX_OUTPUT_DIRECTORY}. Close the application and retry the build.")
    endif()
  endif()
  message(STATUS "Verified sing-box runtime: ${binary}")
endif()
